### ISSUE TITLE
Wrong parameters for Exception (parent constructor)

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [payutc/php-client#7]
I do not exactly know if this issue is regarding the client, the PayUtc server, or Nemopay itself, but I am just using the client, this is the reason I open it here.

When I call the php client with unvalid or unexisting PayUtc product identifiers, the thrown exception is unvalid for the client, which causes an uncatchable PHP 500, fatal error.

The error comes from the status, which should be an integer, and is apparently an array containing an integer.

The client method that I use :

    // The PayutcClient, any class extending AutoJsonClient
    class PayutcClient extends AutoJsonClient
    {
        // [...]
    }

    // The controller logic
    $payutcClient = new PayutcClient();

    $transaction = $payutcClient->createTransaction(array(
        'fun_id' => [a valid fundation id, integer],
        'items' => json_encode(array(array(123456789))), // For instance, might be any unexisting product ID
        'return_url' => 'http://what-ever-app.com/transaction/X/validation/',
        'callback_url' => 'http://what-ever-app.com/transaction/X/callback/',
        'mail' => 'guest@what-ever-app.com/'
    ));

**EDIT : The transaction call works fine as long as the parameter is valid ! So this error does not come from the PayutcClient class.**

I took a screenshot of the FatalErrorException catched by Symfony (but I'm not supposed to handle it anyway)

<img width="1010" alt="payutc-client-exception" src="https://cloud.githubusercontent.com/assets/1577155/9061497/6bd4a1e0-3abc-11e5-9627-14c5ae1846f0.png" />

And when I debug the variables received by the JsonException class :

<img width="251" alt="nemopay-exception" src="https://cloud.githubusercontent.com/assets/1577155/9061502/70a7576c-3abc-11e5-9034-1be1e0660ef8.png" />

I guess the expected code here should be the integer value "42", instead of an array containing this value.

**Comment by mattgu74** [comment]
Hey @Flo-Schield-Bobby,
The server wait an array of tuple (Item_id, Qty), not an array of array containing a single item.

In your example : 
    'items' => json_encode(array(array(123456789))), // For instance, might be any unexisting product ID

should be : 
    'items' => json_encode(array(array(123456789, 1))), // For instance, might be any unexisting product ID

**Comment by Flo-Schield-Bobby** [comment]
Hey @mattgu74, I had wrong informations about it, thanks for the information, I'll update this point :)

However I keep thinking the client should never be the cause of a PHP 500 error, but rather an Exception, whatever are the informations sent to the server ;)

**Comment by trecouvr** [comment]
Thank you for the report. This is indeed a probem on the server side, the code should notre be an array. We'll fix it in the week I keep you posted.
